services:
  tdp:
    build: .
    env_file: .env
    working_dir: /app
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
      # при желании: - db_data:/app/db   (если вынесем sqlite в поддиректорию)
    restart: unless-stopped

  caddy:
    image: caddy:2
    depends_on:
      - tdp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - static_data:/var/www/static
      - media_data:/var/www/media
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  static_data:
  media_data:
  caddy_data:
  caddy_config:
  # db_data:
