services:
  tdp-web:
    container_name: tdp-web
    build:
      context: .
      args:
        DJANGO_ENV: prod
    env_file:
      - .env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    expose:
      - "8000"
    volumes:
      - /srv/data_tdp:/data
      - /srv/media_tdp:/app/media
      - /srv/static_tdp:/app/staticfiles
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
