# Generated by Django 5.2.5 on 2025-08-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название файла/прайса (опционально)', max_length=200)),
                ('file', models.FileField(help_text='PDF файл с актуальными ценами', upload_to='prices/')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, чтобы этот файл был текущим для скачивания')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', '-uploaded_at'],
            },
        ),
    ]
