# Generated by Django 5.2.5 on 2025-09-01 05:45

import django.db.models.deletion
from django.db import migrations, models
 
def copy_service_categories(apps, schema_editor):
    CoreCategory = apps.get_model('core', 'Category')
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    for cat in CoreCategory.objects.all():
        ServiceCategory.objects.create(
            id=cat.id,
            name=cat.name,
            slug=cat.slug,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_price_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.servicecategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
            },
        ),
    migrations.RunPython(copy_service_categories, reverse_code=migrations.RunPython.noop),
    migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory', verbose_name='Категория услуги'),
        ),
    ]
