# Generated by Django 5.2.5 on 2025-09-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecategory_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.servicecategory', verbose_name='Категории услуг'),
        ),
    ]
