# Generated by Django 5.2.5 on 2025-09-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_category_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='excluded',
            field=models.TextField(blank=True, help_text='Список того, что не включено в услугу', verbose_name='Что не включено'),
        ),
        migrations.AddField(
            model_name='service',
            name='included',
            field=models.TextField(blank=True, help_text='Список того, что включено в услугу', verbose_name='Что включено'),
        ),
        migrations.AddField(
            model_name='service',
            name='info',
            field=models.TextField(blank=True, help_text='Важная информация для клиентов', verbose_name='Полезная информация'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярное'),
        ),
        migrations.AddField(
            model_name='service',
            name='note_price',
            field=models.TextField(blank=True, help_text='Дополнительная информация о ценах', verbose_name='Примечание к цене'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_old_adult',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_old_child',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0.00–5.00', max_digits=3, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='service',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во отзывов'),
        ),
    ]
