# Generated by Django 5.2.5 on 2025-09-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_excluded_service_included_service_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='supplier',
            field=models.CharField(blank=True, help_text='Внутренняя информация для админов и менеджеров', max_length=200, verbose_name='Поставщик услуги'),
        ),
    ]
