# Generated by Django 5.2.5 on 2025-08-27 07:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tours', '0002_tour_is_popular_tour_price_old_adult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ('-created_at', 'title'), 'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Фото тура', 'verbose_name_plural': 'Фото тура'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='core.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='tours/covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, max_length=80, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярное'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(blank=True, max_length=160, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='meta_title',
            field=models.CharField(blank=True, max_length=180, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_adult',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена взрослого'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_child',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена детская'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_old_adult',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Старая цена (взрослый)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_old_child',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Старая цена (детский)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0.00–5.00', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во отзывов'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='short_desc',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tours', to='core.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube-видео'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='tours/gallery/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_active', '-created_at'], name='tour_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['slug'], name='tour_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['category', 'is_active'], name='tour_category_active_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_popular', '-created_at'], name='tour_popular_idx'),
        ),
        migrations.AddIndex(
            model_name='tourimage',
            index=models.Index(fields=['tour', 'order'], name='tourimage_tour_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.CheckConstraint(condition=models.Q(('price_old_adult__isnull', True), ('price_old_adult__gte', models.F('price_adult')), _connector='OR'), name='tour_old_adult_ge_new'),
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.CheckConstraint(condition=models.Q(('price_old_child__isnull', True), ('price_old_child__gte', models.F('price_child')), _connector='OR'), name='tour_old_child_ge_new'),
        ),
        migrations.AddConstraint(
            model_name='tourimage',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='tourimage_order_nonnegative'),
        ),
    ]
