# Generated by Django 5.2.5 on 2025-08-28 05:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_options_alter_tourimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена дополнительных услуг'),
        ),
    ]
