# Generated by Django 5.2.5 on 2025-09-01 05:45

import django.db.models.deletion
from django.db import migrations, models

def copy_tour_categories(apps, schema_editor):
    CoreCategory = apps.get_model('core', 'Category')
    TourCategory = apps.get_model('tours', 'TourCategory')
    for cat in CoreCategory.objects.all():
        TourCategory.objects.create(
            id=cat.id,
            name=cat.name,
            slug=cat.slug,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_add_price_extra'),
    ]

    operations = [
    migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tours.tourcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория тура',
                'verbose_name_plural': 'Категории туров',
            },
        ),
    migrations.RunPython(copy_tour_categories, reverse_code=migrations.RunPython.noop),
    migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.tourcategory', verbose_name='Категория тура'),
        ),
    ]
