# Generated by Django 5.2.5 on 2025-09-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tourcategory_alter_tour_category'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tour',
            name='tour_category_active_idx',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
        migrations.AddField(
            model_name='tour',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.tourcategory', verbose_name='Категории туров'),
        ),
    ]
