# Generated by Django 5.2.5 on 2025-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_tour_tour_category_active_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='excluded',
            field=models.TextField(blank=True, help_text='Список того, что не включено в тур', verbose_name='Что не включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included',
            field=models.TextField(blank=True, help_text='Список того, что включено в тур', verbose_name='Что включено'),
        ),
        migrations.AddField(
            model_name='tour',
            name='info',
            field=models.TextField(blank=True, help_text='Важная информация для туристов', verbose_name='Полезная информация'),
        ),
        migrations.AddField(
            model_name='tour',
            name='note_price',
            field=models.TextField(blank=True, help_text='Дополнительная информация о ценах', verbose_name='Примечание к цене'),
        ),
    ]
