# Generated by Django 5.2.5 on 2025-09-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tour_excluded_tour_included_tour_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Изображение тура', 'verbose_name_plural': 'Изображения туров'},
        ),
        migrations.RemoveConstraint(
            model_name='tourimage',
            name='tourimage_order_nonnegative',
        ),
        migrations.RenameIndex(
            model_name='tourimage',
            new_name='tour_image_order_idx',
            old_name='tourimage_tour_order_idx',
        ),
        migrations.AddField(
            model_name='tour',
            name='supplier',
            field=models.CharField(blank=True, help_text='Внутренняя информация для админов и менеджеров', max_length=200, verbose_name='Поставщик тура'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Необязательная подпись к изображению', max_length=200, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(help_text='Рекомендуемый размер: 1200x800px', upload_to='tours/gallery/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше = выше)', verbose_name='Порядок'),
        ),
    ]
